### ISSUE TITLE
Issues with button lighting up during ride searching

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/scoop-ios#37]
It appears that the order in which inputs are filled out during ride searching has some sort of impact as to whether the button lights up 

Expected Behavior (top to bottom data entry)

https://user-images.githubusercontent.com/22649594/234143136-c90c8a08-abda-4062-a132-470520496c3a.MP4

Weird behavior (bottom to top)

https://user-images.githubusercontent.com/22649594/234143156-817c6061-16cd-4ba9-b141-f30eb086d886.MP4

**Comment by rs929** [comment]
https://github.com/cuappdev/scoop-ios/pull/56
