### ISSUE TITLE
Onboarding values inaccurately displayed on profile

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/scoop-ios#40]
Song and snack on my profile are floats:

<img src="https://user-images.githubusercontent.com/22649594/234144351-9bfc42c8-a3bd-43d7-85fe-a24f0937004a.PNG" height=400 width=200 />

I believe the floating points represent the values that my sliders should have, which are also inaccurate

**Comment by rs929** [comment]
Wait Archit, did you edit the prompts multiple times during onboarding?

**Comment by Archit404Error** [comment]
Yeah I definitely did

**Comment by rs929** [comment]
Alright perfect, I think I see the issue, will address now

**Comment by rs929** [comment]
Addressed in:
https://github.com/cuappdev/scoop-ios/pull/41
